workspace(
    name = "rules_typescript_gapic",
)

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock", "pnpm_repository")
npm_translate_lock(
  name = "npm",
  pnpm_lock = ":pnpm-lock.yaml",
  data = [":package.json"],
)

load("@npm//:repositories.bzl", "npm_repositories")
npm_repositories()
pnpm_repository(name = "pnpm")
